Repository Algorithm-Squad/Algorithm, pull requests merged in 2023-10, with the labels that each got.

#142 litae / 37주차 / 2문제
  src/weekly38/litae/programmers/베스트앨범.ts
  src/weekly38/litae/programmers/신고 결과 받기.ts
Labels: PGS

#140 Den / 37주차 / 2문제
  src/weekly37/den/leetcode/139_WordBreak.js
  src/weekly37/den/programmers/신고결과받기.js
Labels: LTC, PGS

#139 Nanii / 37주차 / 2문제
  src/weekly37/nanii/leetCode/139_Word Break.ts
  src/weekly37/nanii/programmers/신고결과받기.ts
Labels: LTC, PGS

#145 litae / 37주차 / 2문제
  src/weekly37/litae/programmers/베스트 앨범.ts
  src/weekly37/litae/programmers/신고 결과 받기.ts
Labels: PGS

#146 Nanii / 38주차 / 1.5문제
  src/weekly38/nanii/leetCode/739. Daily Temperatures.ts
  src/weekly38/nanii/programmers/이모티콘할인행사.ts
Labels: LTC, PGS

#147 Poco / 38주차 / 2문제
  src/weekly38/poco/leetCode/739_DailyTemperatures.js
  src/weekly38/poco/programmers/이모티콘할인행사.js
Labels: LTC, PGS

#148 litae / 38주차 / 1.5문제
  src/weekly38/litae/leetcode/739. Daily Temperatures.ts
  src/weekly38/litae/programmers/이모티콘 할인행사.ts
Labels: LTC, PGS

#150 Den / 39주차 / 2문제
  src/weekly39/den/leetcode/198_House Rover.js
  src/weekly39/den/leetcode/71_Simplify Path.js
Labels: LTC

#151 litae / 39주차 / 1.5문제
  src/weekly39/litae/leetcode/198. House Robber.ts
  src/weekly39/litae/leetcode/71. Simplify Path.ts
Labels: LTC

#149 Poco / 39주차 / 2문제
  src/weekly39/poco/leetCode/198_HouseRobber.js
  src/weekly39/poco/leetCode/71_SimplifyPath.js
Labels: LTC
