Repository Algorithm-Squad/Algorithm, pull requests merged in 2023-01, with the labels that each got.

#2 Ethan / 1월 1주차 / 5문제
  src/weekly1/ethan/leetCode/146_Permutations.ts
  src/weekly1/ethan/leetCode/169_MajorityElement.ts
  src/weekly1/ethan/leetCode/283_MoveZeroes.ts
  src/weekly1/ethan/leetCode/35_SearchInsertPosition.ts
  src/weekly1/ethan/leetCode/39_CombinationSum.ts
Labels: LTC

#8 Jace / 1월 1주차 / 2문제
  src/weekly1/jace/leetCode/169_MajorityElement.js
  src/weekly1/jace/leetCode/283_MoveZeroes.js
Labels: LTC

#3 Poco / 1주차 / 4문제
  src/weekly1/poco/leetCode/169_MajorityElement.js
  src/weekly1/poco/leetCode/283_MoveZeroes.js
  src/weekly1/poco/leetCode/46_Permutations.js
Labels: LTC

#4 Nanii / 1월 1주차 / 4문제
  src/weekly1/nanii/leetCode/169_MajorityElement.js
  src/weekly1/nanii/leetCode/283_MoveZeroes.js
  src/weekly1/nanii/leetCode/35_SearchInsertPosition.js
  src/weekly1/nanii/leetCode/39_CombinationSum.js
Labels: LTC

#6 Den / 1월 1주차 / 3문제
  src/weekly1/den/leetcode/169_MajorityElement.js
  src/weekly1/den/leetcode/283_MoveZeroes.js
  src/weekly1/den/leetcode/35_SearchInsertPosition.js
  src/weekly1/den/leetcode/39_CombinationSum.js
  src/weekly1/den/leetcode/46_Permutations.js
Labels: LTC

#9 Ethan / 2 주차 / 3 문제
  src/weekly2/ethan/leetCode/20_ValidParentheses.ts
  src/weekly2/ethan/leetCode/49_GroupAnagrams.ts
  src/weekly2/ethan/programmers/신규아이디추천.ts
Labels: LTC, PGS

#12 poco/ 2주차/ 3문제
  src/weekly2/poco/leetCode/20_ValidParentheses.js
  src/weekly2/poco/leetCode/49_GroupAnagrams.js
  src/weekly2/poco/programmers/신규아이디추천.js
Labels: LTC, PGS

#11 Nanii / 2주차 / 3문제
  src/weekly2/nanii/leetCode/20_ValidParentheses.js
  src/weekly2/nanii/leetCode/49_GroupAnagrams.js
  src/weekly2/nanii/programmers/신규아이디추천_Lv1[Array].js
  src/weekly2/nanii/programmers/신규아이디추천_Lv1[String].js
Labels: LTC, PGS

#10 Den / 2주차 / 3문제
  src/weekly2/den/leetcode/20_ValidParentheses.js
  src/weekly2/den/leetcode/49_GroupAnagrams.js
  src/weekly2/den/programmers/신규아이디추천.js
Labels: LTC, PGS

#14 litae / 2주차 / 3문제
  src/weekly2/litae/leetCode/20_ValidParentheses.js
  src/weekly2/litae/leetCode/49_GroupAnagrams.js
  src/weekly2/litae/programmers/2021kakao_RecommendNewID.js
Labels: LTC, PGS

#15 Nanii / 3주차 / 2문제
  src/weekly3/nanii/baekjoon/2309_일곱난쟁이.js
  src/weekly3/nanii/programmers/소수찾기_Lv2.js
Labels: PGS, BOJ

#17 Den / 3주차 / 2문제
  src/weekly3/den/baekjoon/일곱난쟁이.js
  src/weekly3/den/programmers/모음사전.js
Labels: PGS, BOJ

#18 Ethan / 3주차 / 3 문제
  src/weekly3/ethan/boj/2309_일곱난쟁이.js
  src/weekly3/ethan/programmers/모음사전.ts
  src/weekly3/ethan/programmers/소수찾기.ts
Labels: PGS, BOJ

#19 Poco / 3주차 / 2문제
  src/weekly3/poco/BOJ/일곱난쟁이.js
  src/weekly3/poco/programmers/소수찾기.js
Labels: PGS, BOJ

#16 litae / 3주차 / 2문제
  src/weekly3/litae/baekjoon/2309_TheSevenDwarfs.js
  src/weekly3/litae/programmers/완전탐색_SearchPrime.js
Labels: PGS, BOJ

#20 Den / 4주차 / 3문제
  src/weekly4/den/baekjoon/1914_하노이탑.js
  src/weekly4/den/leetcode/09_FibonacciNumber.js
  src/weekly4/den/programmers/콜라문제.js
Labels: LTC, PGS, BOJ

#21 Nanii / 4주차 / 2.5문제
  src/weekly4/nanii/baekjoon/1914_하노이탑.js
  src/weekly4/nanii/leetCode/509_FibonacciNumber.js
  src/weekly4/nanii/programmers/콜라문제.js
Labels: LTC, PGS, BOJ

#22 litae / 1월 4주차 / 2문제
  src/weekly4/litae/leetcode/509_ FibonacciNumber.js
  src/weekly4/litae/programmers/Cola.js
Labels: LTC, PGS

#23 Poco / 4주차 / 2문제
  src/weekly4/poco/leetCode/509_FibonacciNumber.js
  src/weekly4/poco/programmers/콜라문제_Lv1.js
Labels: LTC, PGS
